project:
  type: website
  output-dir: docs

website:
  title: "cndwg_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Authorship.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

