project:
  type: website
  output-dir: docs

website:
  title: "Marine Consumer Nutrient Dynamics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Authorship.qmd
      - about.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

