---
title: "Marine Consumer Nutrient Dynamics LTER Synthesis Working Group"
---

### **Consumer-mediated nutrient dynamics of marine ecosystems under the wake of global change**

Increases in the frequency and severity of disturbance events as a result of global change are altering population and community dynamics of marine animals. Given that animals are key recyclers of nutrients in many ecosystems, these ecological impacts may have consequences for ecosystem function. Consumer-mediated nutrient dynamics (CND) are an integral part of biogeochemical cycles, but to-date long-term studies are lacking. Without long-term data across large spatial scales, it is difficult to predict how ecosystems will respond to disturbances. The synthesis group plans to estimate CND over broad spatiotemporal scales by integrating empirical models of consumer nutrient excretion and egestion with time-series of consumer populations across ten marine and coastal LTER sites. They will address two main objectives:

1.  characterizing spatiotemporal patterns in the magnitude and variability of CND and;

2.  evaluating the resilience of CND to variable disturbance events.

This is a revised proposal based on positive feedback of the group's 2018 submission and input from colleagues during a cross-site workshop at the 2022 LTER ASM. With funds from LTER LNO, this diverse working group will synthesize LTER data to improve understanding of CND over broad spatiotemporal scales under the wake of global change.
